kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    run: nginx
    app: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: nginx
    app: nginx
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    run: nginx-service
    app: nginx-service
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: https
      targetPort: 443
      port: 443
  selector:
    run: nginx-service
    app: nginx-service
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx_alpine
        imagePullPolicy: Never
        name: nginx
        env:
        - name: SSH_USER
          value: admin
        - name: SSH_PASSWORD
          value: admin
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh