apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    run: phpmyadmin
    app: phpmyadmin
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    run: phpmyadmin
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: etopian/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOSTNAME
              value: mysql
            - name: PMA_USERNAME
              value: root
            - name: PMA_PASSWORD
              value: password